version : "3.8"
services:
  app:
    image: "mile1217/mile-server"
    container_name: mile
    ports:
        - "8080:8080"
    networks:
      - mile-app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mile-app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - app
    networks:
      - mile-app-network
networks:
  mile-app-network:
    driver: bridge