services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
       - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app-tier